taw/magic-preconstructed-decks

.gitignore
data/cmd/cm2/Breed Lethality.txt
data/cmd/cm2/Built From Scratch.txt
data/cmd/cm2/Devour for Power.txt
data/cmd/cm2/Wade into Battle.txt
lib/sets.rb

This adds the decklists for CM2, including foil information sourced from [this unboxing video](https://www.youtube.com/watch?v=n3QjGzXWsd4).
I've also added `decks.json` to the gitignore, since it's generated by the validation but not in the repo.

Add Commander Anthology Volume II

---

data/jumpstart/jmp/Spellcasting (1).txt

"Spellcasting (1)" Jumpstart deck was misspelled as "Spellingcasting (1)" in both the filename and in the txt file itself. Fixed this typo.
Not sure if there are any other references that need to be updated.

Updated misspelled Jumpstart deck

---

data/intro/ogw/Twisted Reality.txt
data/intro/ogw/Vicious Cycle.txt

Updated OGW Intro Packs with specific versions of Wastes along with counts for each.
The Wastes in the OGW Intro Packs are different than the ones in OGW Booster Packs. The Wastes in Booster Packs are full art, the ones in the Intro Packs are regular art and are exclusive to these decks making them more desirable. There are 2 different arts and there appears to be an equal distribution in each deck with half of the wastes being one art, half the other.
Here are openings on YouTube that I used for proof:
https://youtu.be/uy_3tKXQ8Mk?t=197
https://youtu.be/KrF5BZ5rFaA?t=226

Updated OGW Intro Pack decklists with the specific versions of Wastes

---

data/cmd/40k/Forces of the Imperium.txt
data/cmd/40k/Necron Dynasties.txt
data/cmd/40k/The Ruinous Powers.txt
data/cmd/40k/Tyranid Swarm.txt

Hello! 
I was taking a look at the decks and I noticed that, same as #14 , there are a few other cards that change the printing depending on the deck it appears. These are the cards: 
```
Mountain
Swamp
Island
Command Tower
Mind Stone
Commander's Sphere
Wayfarer's Bauble
Talisman of Dominance
Arcane Signet
```
Another issue I noticed is the number chosen for the main and alternative commanders. The ones picked are the surge foil versions of the cards, but those only appear in the $100+ Collector's edition of the deck precons. I changed them to the regular foil versions.
I splitted the commits in case it helps reviewing.

Fix 40k deck printings

---

data/cmd/40k/Forces of the Imperium.txt
data/cmd/clb/Draconic Dissent.txt
data/cmd/clb/Exit from Exile.txt
data/cmd/clb/Mind Flayarrrs.txt
data/cmd/clb/Party Time.txt
data/game-night/gn3/Boundless Elves.txt
data/game-night/gn3/Dark Sacrifice.txt
data/game-night/gn3/Draconic Fury.txt
data/game-night/gn3/Glorious Combat.txt
data/game-night/gn3/Political Trickery.txt

Hello!
It looks like the Forces of the Imperium deck is picking 2 regular cards as surge foil.
The reason seems to be that the frame effect called "miracle" is missing from the surge foil printing in the Scryfall API, probably due to a bug. That results in the script prioritizing the surge foil one.
I hardcoded the collector number so that they are picked regardless of the frame effect is this situation.
Normal printing has frame effects
https://api.scryfall.com/cards/f78f5b9a-bd80-41e9-873e-826628dc44a7?format=json&pretty=true
Surge foil printing doesn't have frame effects
https://api.scryfall.com/cards/3698b37f-0d86-42ea-9031-8f7e54b5d953?format=json&pretty=true

Fix Forces of the Imperium (40K) printings and foil printings from CLB and GN3

---

data/cmd/40k/Forces of the Imperium Collector's Edition.txt
data/cmd/40k/Necron Dynasties Collector's Edition.txt
data/cmd/40k/The Ruinous Powers Collector's Edition.txt
data/cmd/40k/Tyranid Swarm Collector's Edition.txt

The main and secondary commanders from the 40k collector's edition are the 1-8 numbered cards, which are surge foil.

Fix surge foil commanders

---

data/cmd/brc/Mishra's Burnished Banner.txt
data/cmd/brc/Urza's Iron Alliance.txt

The Mishra's deck was missing the second foil commander.

Update alternative commander as foil

---

data/starter/afr/Rough and Tumble.txt
data/starter/afr/Sneak Attack.txt
data/starter/snc/Red-Green Starter Deck.txt
data/starter/snc/White-Blue Starter Deck.txt

There are 2 decks that were missing, listed here https://mtg.fandom.com/wiki/2021_Arena_Starter_Kit
I've fixed as well the 2 foil cards that are in the 2022 Starter Kit. 
Regarding the 2 decks from Starter Kit 2022, what do you think about renaming them? 
Red-Green Starter Deck -> Earth Shakers
White-Blue Starter Deck -> Up and Away
Source https://mtg.fandom.com/wiki/2022_Starter_Kit
As they are it can be a bit hard to find them because of the name and because they are categorized inside Streets of New Capenna

Arena Starter Kit 2021

---

data/starter/m21/Mono Black.txt
data/starter/m21/Mono Green.txt

Added the Arena Starter Kit (2020) decks. https://mtg.fandom.com/wiki/Core_Set_2021/Arena_Starter_Kit
Unfortunately they do not have a particular name, simply Mono Green and Mono Black.

Core Set 2021 / Arena Starter Kit 2020

---

data/pioneer/bro/Orzhov Humans.txt

It looks like this Pioneer Challenger deck has some printing inconsistencies.
I don't have an official online source of the exact printings other than the word of a person that owns the deck.
These are the changes:
```
Duress              MID -> M21
Kitesail Freebooter M21 -> XLN
Mutavault           M14 -> CLB
Plains              BRO -> DMU
```

Fix Orzhov Humans printings

---

data/starter/9ed/Gold Deck.txt
data/starter/9ed/Silver Deck.txt

The 9ED decks from https://mtg.fandom.com/wiki/Ninth_Edition/Core_Game were missing a release date.
We could add the date that appears in the Amazon site August 9th. The set itself released July 29th, so it could be accurate.
https://www.amazon.com/Magic-Gathering-Core-Wizards-Coast/dp/0786938536

Add date to 9ed decks

---

data/starter-kit/ltr/Mordor - Black-Red.txt

Similar to https://github.com/taw/magic-preconstructed-decks/pull/53
There was an extra printing with the LTC version in the starter deck.

Fix "Feed The Swarm" version in LTR Starter deck

---

data/cmd/phed/Heads I Win, Tails You Lose.txt

This picked the thick variant, which is not tournament legal.

phed: Fix collector number for the two commanders

---

data/arena-kit/afr/Sneak Attack.txt

Archmage Emeritus was pointing to an only foil promo in the Starter Kit deck.
It should be the regular version of that card.
Promo: https://scryfall.com/card/stx/377/archmage-emeritus
Regular: https://scryfall.com/card/stx/37/archmage-emeritus

Fix typo in card number

---

data/dotp/dpa/Ears of the Elves.txt
data/dotp/dpa/Eyes of Shadow.txt
data/dotp/dpa/Hands of Flame.txt
data/dotp/dpa/Teeth of the Predator.txt
data/dotp/dpa/Thoughts of the Wind.txt

Anything after the dash is redundant and this brings this set closer to how other decks are handled (ie a short identifiable name).

Rename DPA decks to only contain the name of the deck

---

data/sdcc/SDCC 2013 Planeswalker Set.txt
data/sdcc/SDCC 2014 Planeswalker Set.txt
data/sdcc/SDCC 2015 Planeswalker Set.txt
data/sdcc/SDCC 2016 Zombie Planeswalker Set.txt
data/sdcc/SDCC 2017 Planeswalker Set.txt
data/sdcc/SDCC 2018 Planeswalker Set.txt
data/sdcc/SDCC 2019 Dragon's Endgame.txt

the 2013-2018 don't have an official name, so i went with the standard scheme on tcg
I didn't add "Set" to the last box of 2019, but if needed for consistency i can add it

Add SDCC sets

---

data/sld/sld/Valentines Day 2021 foil.txt
data/sld/sld/Valentines Day 2021.txt

This card was never shipped so it shouldn't count towards the decklist. The DISPLAY note should be enough.
Alternatively we could set the count to 0 but I don't know how the system will react (and seems counter intuitive)

sld: Remove card that is not actually present in the products

---

data/cmd/m3c/Eldrazi Incursion.txt

Scryfall and MTGJSON data had an issue with the non foil version of Hideous Taskmaster. This now points to the correct version, number 109 is no longer in the database.

Update Hideous Taskmaster card version

---

data/challenger/q07/Gruul Stompy.txt

There was a typo on a card fix from the last PR. I missed the warning when generating the decks json data

fix non existing printing

---

data/starter-std/8ed/Silver Deck.txt
data/starter-std/9ed/Silver Deck.txt

part of https://github.com/taw/magic-search-engine/issues/345

Set Vizzerdrix number in starter decks to reduce warnings
