- data/welcome/m19/Core 2019 Welcome Deck - Black.txt
- data/welcome/m19/Core 2019 Welcome Deck - Blue.txt
- data/welcome/m19/Core 2019 Welcome Deck - Green.txt
- data/welcome/m19/Core 2019 Welcome Deck - Red.txt
- data/welcome/m19/Core 2019 Welcome Deck - White.txt
Decklists sourced from [Gamepedia](https://mtg.gamepedia.com/Core_Set_2019/Welcome_decks).
> Add Core Set 2019 welcome decks

- data/cmd/40k/Forces of the Imperium.txt
- data/cmd/40k/Necron Dynasties.txt
- data/cmd/40k/The Ruinous Powers.txt
- data/cmd/40k/Tyranid Swarm.txt
> Fix Sol Ring card numbers in 40k decks

- data/challenger/neo/Dimir Control.txt
- data/challenger/neo/Mono White Aggro.txt
- data/cmd/clb/Draconic Dissent.txt
- data/cmd/clb/Exit from Exile.txt
- data/cmd/clb/Mind Flayarrrs.txt
- data/cmd/clb/Party Time.txt
- data/cmd/ncc/Bedecked Brokers.txt
- data/cmd/ncc/Cabaretti Cacophony.txt
- data/cmd/ncc/Maestros Massacre.txt
- data/cmd/ncc/Obscura Operation.txt
- data/cmd/ncc/Riveteers Rampage.txt
Indicate the exact printing in some of the precons to avoid the warnings
> Fix warnings in some precons

- data/cmd/brc/Mishra's Burnished Banner.txt
- data/cmd/brc/Urza's Iron Alliance.txt
- lib/sets.rb
The upcoming commander deck lists.
> The Brothers' War Commander decks

- data/cmd/scd/Chaos Incarnate.txt
- data/cmd/scd/Draconic Destruction.txt
- data/cmd/scd/First Flight.txt
- data/cmd/scd/Grave Danger.txt
- data/cmd/scd/Token Triumph.txt
Decks from https://magic.wizards.com/en/news/announcements/starter-commander-decks-decklists-2022-10-20
> Starter Commander decks

- data/cmd/moc/Call for Backup.txt
- data/cmd/moc/Cavalry Charge.txt
- data/cmd/moc/Divine Convocation.txt
- data/cmd/moc/Growing Threat.txt
- data/cmd/moc/Tinker Time.txt
Commander decks from the latest set.
> March of the Machine decks

- data/challenger/neo/Dimir Control.txt
- data/challenger/neo/Mono White Aggro.txt
- data/cmd/brc/Mishra's Burnished Banner.txt
- data/cmd/onc/Corrupting Influence.txt
- data/cmd/onc/Rebellion Rising.txt
- data/jumpstart-19/one/Mite-y 1.txt
- data/jumpstart/j22/Boneyard 1.txt
- data/jumpstart/j22/Boneyard 2.txt
- data/jumpstart/j22/Dragons 1.txt
- data/jumpstart/j22/Goblins 1.txt
- data/jumpstart/j22/Goblins 2.txt
- data/jumpstart/j22/Goblins 3.txt
- data/jumpstart/j22/Goblins 4.txt
- data/jumpstart/j22/Law 1.txt
- data/jumpstart/j22/Morbid 1.txt
- data/jumpstart/j22/Morbid 2.txt
- data/jumpstart/j22/Teamwork 1.txt
- data/jumpstart/j22/Teamwork 2.txt
- data/jumpstart/j22/Unlucky Thirteen.txt
- data/jumpstart/j22/Zombies 2.txt
Update card versions of Jumpstart cards to resolve Issue https://github.com/taw/magic-preconstructed-decks/issues/23
Resolved some tangential "cannot resolve" problems for other decks.
> Fix unresolved card variations

- data/arena-promo/one/Vivien's Hunt.txt
- data/arena-starter/anb/Angelic Army.txt
- data/arena-starter/anb/Azure Skies.txt
- data/arena-starter/anb/Dome Destruction.txt
- data/arena-starter/anb/Forest's Might.txt
- data/arena-starter/anb/Out for Blood.txt
- data/box/cc2/Commander Collection Black Premium.txt
- data/box/cc2/Commander Collection Black.txt
- data/sld/slc/30th Anniversary Countdown Kit.txt
- lib/deck_types.rb
Add supplemental products from 2022
Fix missing dates on arena decks
> Supplemental sets 2022

- data/box/ced/Collectors' Edition.txt
- data/box/cei/Intl. Collectors' Edition.txt
- data/box/cm1/Commander's Arsenal Oversized.txt
- data/box/cm1/Commander's Arsenal.txt
not sure if CM1 is right since the oversized cards are in a separate edition (OCM1)
> CED, CEI, CM1 box sets

- data/cmd/who/Blast from the Past.txt
- data/cmd/who/Masters of Evil.txt
- data/cmd/who/Paradox Power.txt
- data/cmd/who/Timey-Wimey.txt
- lib/sets.rb
https://magic.wizards.com/en/news/announcements/magic-the-gathering-doctor-who-commander-decklists
> Dr Who Commander precons

- data/duel/dd2/Chandra Japanese.txt
- data/duel/dd2/Jace Japanese.txt
Related to https://github.com/mtgjson/mtg-sealed-content/issues/100
> DD2: Separate the Japanese promos in their own decks

- data/starter-std/5ed/Deck A.txt
- data/starter-std/5ed/Deck B.txt
- data/starter-std/6ed/Deck A.txt
- data/starter-std/6ed/Deck B.txt
- lib/deck_types.yaml
5th and 6th edition starter decks
> Starter Decks

- data/cmd/mkc/Blame Game.txt
- data/cmd/mkc/Deadly Disguise.txt
- data/cmd/mkc/Deep Clue Sea.txt
- data/cmd/mkc/Revenant Recon.txt
Commander decks for Murders at Karlov Manor
> Murders at Karlov Manor Commander

- data/sld/sld/Pride Across the Multiverse.txt
> SLD Pride Across the Multiverse: All cards are nonfoil in the nonfoil set

- data/box/pvan/First Series.txt
- data/box/pvan/Fourth Series.txt
- data/box/pvan/Second Series.txt
- data/box/pvan/Third Series.txt
not sure if i have to add a deck type but i see pvan listed somewhere
> Add Vanguard series

- data/cmd/m3c/Creative Energy.txt
- data/cmd/m3c/Eldrazi Incursion.txt
- data/cmd/m3c/Graveyard Overdrive.txt
- data/cmd/m3c/Tricky Terrain.txt
Preliminary input data for the commander precons. https://magic.wizards.com/en/news/announcements/modern-horizons-3-commander-decklists
If we want to include the Collector's Edition versions, we would need to also include the card numbers to target the ripple foil card numbers.
> Modern Horizons 3 Commander precons 

- data/arena-starter/acr/Ancient Arsenal.txt
- data/arena-starter/acr/Brotherhood Agents.txt
I couldn't test these because ACR isn't recognized by the decks json builder
> ACR starter decks

- data/welcome-booster/7ed/Sampler Booster.txt
- data/welcome-booster/9ed/Sampler Booster.txt
If you can find any information about the 8th edition sampler booster let me know. I cannot find ANY info about it besides that it had 10 cards.
> Add some sampler boosters

- data/sld/sld/Artist Series Livia Prima foil.txt
forgot from the big cleanse a few weeks ago
> SLD: Remove one leftover sideboard card

- data/sld/sld/Lil Legends.txt
- data/sld/sld/The Beauty of the Beasts.txt
> Sld missing two decks

- data/sld/sld/Marvel's Black Panther foil.txt
- data/sld/sld/Marvel's Black Panther.txt
- data/sld/sld/Marvel's Captain America foil.txt
- data/sld/sld/Marvel's Captain America.txt
- data/sld/sld/Marvel's Iron Man foil.txt
- data/sld/sld/Marvel's Iron Man.txt
- data/sld/sld/Marvel's Storm foil.txt
- data/sld/sld/Marvel's Storm.txt
- data/sld/sld/Marvel's Wolverine foil.txt
- data/sld/sld/Marvel's Wolverine.txt
I used the flavor names and added tokens. I did it based on how The Walking Dead SLDuses flavor names and has tokens.
> Add Secret Lair Marvel Superdrop

- data/sld/sld/Cats Are Better Than Dogs foil.txt
- data/sld/sld/Cats Are Better Than Dogs.txt
- data/sld/sld/Dogs Are Better Than Cats foil.txt
- data/sld/sld/Dogs Are Better Than Cats.txt
- data/sld/sld/Garden Buds foil.txt
- data/sld/sld/Garden Buds.txt
- data/sld/sld/High Class of '87 foil.txt
- data/sld/sld/High Class of '87.txt
- data/sld/sld/Marvel's Deadpool foil.txt
- data/sld/sld/Marvel's Deadpool.txt
- data/sld/sld/Oishii Tokens オイシイ！ トークン foil.txt
- data/sld/sld/Oishii Tokens オイシイ！ トークン.txt
- data/sld/sld/Pick 'em and Stick 'em foil.txt
- data/sld/sld/Pick 'em and Stick 'em.txt
- data/sld/sld/SpongeBob SquarePants Internet Sensation foil.txt
- data/sld/sld/SpongeBob SquarePants Internet Sensation.txt
- data/sld/sld/SpongeBob SquarePants Lands Under the Sea foil.txt
- data/sld/sld/SpongeBob SquarePants Lands Under the Sea.txt
- data/sld/sld/SpongeBob SquarePants Legends of Bikini Bottom foil.txt
- data/sld/sld/SpongeBob SquarePants Legends of Bikini Bottom.txt
- data/sld/sld/They Grow Up So Fast foil.txt
- data/sld/sld/They Grow Up So Fast.txt
- data/sld/sld/Tragic Romance foil.txt
- data/sld/sld/Tragic Romance.txt
- data/sld/sld/Twisted Toons foil.txt
- data/sld/sld/Twisted Toons.txt
⚠️I don't know if the oishii file names will break anything - i can just drop the unicode characters
> Add Spongebob and Deadpool drops

- data/arena-starter/m20/Azorius Senate.txt
- data/arena-starter/m20/Boros Legion.txt
- data/arena-starter/m20/Cult of Rakdos.txt
- data/arena-starter/m20/Golgari Swarm.txt
- data/arena-starter/m20/Gruul Clans.txt
- data/arena-starter/m20/House Dimir.txt
- data/arena-starter/m20/Izzet League.txt
- data/arena-starter/m20/Orzhov Syndicate.txt
- data/arena-starter/m20/Selesnya Conclave.txt
- data/arena-starter/m20/Simic Combine.txt
- data/brawl/eld/Faerie Schemes.txt
- data/brawl/eld/Knights' Charge.txt
- data/brawl/eld/Savage Hunter.txt
- data/brawl/eld/Wild Bounty.txt
- data/challenger/q02/Arcane Tempo.txt
- data/challenger/q02/Deadly Discovery.txt
- data/guild-kit/gk1/Boros.txt
- data/guild-kit/gk1/Dimir.txt
- data/guild-kit/gk1/Golgari.txt
- data/guild-kit/gk1/Izzet.txt
- data/guild-kit/gk1/Selesnya.txt
- data/guild-kit/gk2/Azorius.txt
- data/guild-kit/gk2/Gruul.txt
- data/guild-kit/gk2/Orzhov.txt
- data/guild-kit/gk2/Rakdos.txt
- data/guild-kit/gk2/Simic.txt
- data/pw/grn/Ral, Caller of Storms.txt
- data/pw/grn/Vraska, Regal Gorgon.txt
- data/pw/rna/Domri, City Smasher.txt
- data/pw/rna/Dovin, Architect of Law.txt
This is part of #168 , and should address all open Guildgate numbers in various decks! 🎉 
A note on arena precons, I wasn't able to completely doublecheck all the decks but I believe it's a standard 4x of the first version available
> Guildgates collector numbers

- data/arena-kit/m21/Mono Black Amazon.txt
- data/arena-kit/m21/Mono Green Amazon.txt
They only changed a single card in each of them! Lmk if you can think of a better way to represent the variation
> Duplicate M21 Arena Kit decks for the Amazon version

- data/sld/sld/Squishful Thinking Foil Edition.txt
- data/sld/sld/Squishful Thinking.txt
oops
found by the new sldownloader engine!
> SLD: Fix numbers for Squishful Thinking drops
